server:
  port: 8083

spring:
  properties:
  sql.init.mode: always

app:
  kafka:
    servers: localhost:9092
    topic:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1.

